### ISSUE TITLE
High Frequency Limit (1000-20000): Problem in EQ

### ISSUE THREAD

**Issue by ManCaveAudio** [pulento/A1Evo_Electrified#3]
If you can see the all graphs, you can HPF applied or roll off in low end frequencies and null at 20Hz. This is because I tried not to apply 2nd filter (High Frequency Limit (1000-20000) and set it to 0.

I think it is because it was applying frequency range from 10 to 20 Hz. 

Also, it will be great option if you can add HighPass Filter On or Off function.

![image](https://github.com/user-attachments/assets/23d5494a-1968-4045-881f-8c0e6bb82755)

**Comment by pulento** [comment]
Hi,

As I understantd yoy want High Pass LF at something about 20Hz ? You have great bass capabilities there and it seems the naturall rollof of your speakers are well below 20Hz; you want to cut that ? may affect the phase at LF and mess with the aligning algoritms of A1Evo.

Remember the current Beta don't apply any boost between 10-200Hz just the default A1Evo.

BTW no need to graph SW1o which is the vector average of the original Audyssey measurement.

**Comment by pulento** [comment]
No feedback

**Comment by pulento** [comment]
No feedback
